name: CI
on: [ push ]
jobs:
  Validate-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
  Update-Dependency-Baseline:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle5 ]
    permissions:
      contents: write
    # This job only runs when renovate opens the PR
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - name: Update Dependency Guard Baseline
        run: ./gradlew dependencyGuardBaseline
      - name: Commit updated baseline
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update dependency guard baseline"
          file_pattern: '**/dependencies/*.txt'
  Build:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle ]
    # Run this job even if Update-Dependency-Baseline is skipped
    if: always()
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - name: Build
        run: ./gradlew assemble
  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    strategy:
      matrix:
        command: [ detekt detektMain detektTest, lint, spotlessCheck, checkSortDependencies, licensee, releaseComposeCompilerCheck, dependencyGuard ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - name: Lint
        run: ./gradlew ${{ matrix.command }}
  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: ./gradlew test
#      - name: Codecov
#        uses: codecov/codecov-action@v4.5.0
#        with:
#          token: ${{ secrets.CODE_COV_TOKEN  }}
